site_name: PCSX-Redux
site_url: https://pcsx-redux.consoledev.net/
repo_url: https://github.com/grumpycoders/pcsx-redux/
edit_uri: edit/docs/docs/

theme:
  name: material
  palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - search
  - with-pdf:
      output_path: pcsx-redux.pdf

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

extra_css:
    - css/extra.css

nav:
    - 'index.md'
    - 'menus.md'
    - 'compiling.md'
    - 'cli_flags.md'
    - Debugging:
      - 'Debugging/introduction.md'
      - 'Debugging/gdb-server.md'
      - 'Debugging/ghidra.md'
      - 'Debugging/misc-features.md'
      - 'Debugging/vram-viewer.md'
      - 'Debugging/gpu-logger.md'
    - 'mips_api.md'
    - 'web_server.md'
    - Lua:
      - 'Lua/introduction.md'
      - 'Lua/libraries.md'
      - 'Lua/redux-basics.md'
      - 'Lua/rendering.md'
      - 'Lua/file-api.md'
      - 'Lua/web-server.md'
      - 'Lua/memory-and-registers.md'
      - 'Lua/events.md'
      - 'Lua/breakpoints.md'
      - 'Lua/assembler.md'
      - 'Lua/binary.md'
      - 'Lua/case-studies.md'
    - 'openbios.md'
