site_name: PCSX-Redux
site_url: https://pcsx-redux.consoledev.net/
repo_url: https://github.com/grumpycoders/pcsx-redux/
edit_uri: edit/docs/docs/

theme:
  name: material
  palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - search
  - with-pdf:
      output_path: pcsx-redux.pdf
  - mkdocs-simple-hooks:
      hooks:
        on_pre_build: "hooks:build_onepage"

extra_css:
    - css/extra.css

nav:
    - 'index.md'
    - 'menus.md'
    - 'compiling.md'
    - 'cli_flags.md'
    - 'gdb-server.md'
    - 'mips_api.md'
