site_name: PCSX-Redux
site_url: https://pcsx-redux.consoledev.net/
repo_url: https://github.com/grumpycoders/pcsx-redux.git/
edit_uri: edit/docs/docs/

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - search
#  - with-pdf:
#      output_path: pcsx-redux.pdf

extra_css:
    - css/extra.css
