name: Linux CI AUR

on:
  push:
    branches:
      - main
      - aur-package-ci
  pull_request:

jobs:
  build:
    runs-on: arch-latest
    container:
      image: archlinux:latest
    steps:
      - name: Build AUR Package
        run: |
          pacman -S capstone curl ffmpeg freetype2 glfw libuv sdl2 zlib git make pkg-config
          git clone https://aur.archlinux.org/pcsx-redux-git.git
          cd pcsx-redux-git && makepkg
